#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
if {! [info exists ::env(MPIHOME)]} {
  puts stderr "Need to load an mpi module before loading petsc"
  exit 1
}
foreach {x} [glob -directory /opt/petsc/ROLLCOMPILER -tails *] {
  if {[regexp \$x \$::env(MPIHOME)]} {
    set mpi \$x
    break
  }
}
if {! [info exists mpi]} {
  if {[ regexp ScaleMP \$::env(MPIHOME)]} {
      set mpi vsmp
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
foreach {x} [glob -directory /opt/petsc/ROLLCOMPILER/\$mpi -tails *] {
  if {[regexp \$x \$::env(MPIHOME)]} {
    set network \$x
    break
  }
}
if {! [info exists network]} {
  if {[ regexp ScaleMP \$::env(MPIHOME)]} {
      set network ib
  }
}
if {! [info exists network]} {
  puts stderr "No supported network found"
  exit 1
}
module-whatis "petsc_ROLLCOMPILER_\${mpi}_\$network"
module-whatis "Version: VERSION"
prepend-path LD_LIBRARY_PATH /opt/petsc/ROLLCOMPILER/\$mpi/\$network/lib
prepend-path LIBPATH /opt/petsc/ROLLCOMPILER/\$mpi/\$network/lib
setenv PETSCHOME /opt/petsc/ROLLCOMPILER/\$mpi/\$network

END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; if test ! -e .version; then /bin/ln -s .version.VERSION .version; fi )

