ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

ifndef ROLLMPI
  ROLLMPI = rocks-openmpi
endif
MPINAME := $(firstword $(subst /, ,$(ROLLMPI)))

NAME           = sdsc-petsc_$(COMPILERNAME)_$(MPINAME)
VERSION        = 3.6.3
RELEASE        = 4
PKGROOT        = /opt/petsc/$(COMPILERNAME)/$(MPINAME)

SRC_SUBDIR     = petsc

SOURCE_NAME    = petsc
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

BLACS_NAME    = blacs-dev
BLACS_PKG     = $(BLACS_NAME).$(SOURCE_SUFFIX)
BLACS_DIR     = $(BLACS_PKG:%.$(SOURCE_SUFFIX)=%)

FBLASLAPACK_NAME    = fblaslapack
FBLASLAPACK_VERSION = 3.4.2
FBLASLAPACK_PKG     = $(FBLASLAPACK_NAME)-$(FBLASLAPACK_VERSION).$(SOURCE_SUFFIX)
FBLASLAPACK_DIR     = $(FBLASLAPACK_PKG:%.$(SOURCE_SUFFIX)=%)

MUMPS_NAME    = MUMPS
MUMPS_VERSION = 5.0.1
MUMPS_PKG     = $(MUMPS_NAME)_$(MUMPS_VERSION).$(SOURCE_SUFFIX)
MUMPS_DIR     = $(MUMPS_PKG:%.$(SOURCE_SUFFIX)=%)

PASTIX_NAME    = pastix
PASTIX_SUFFIX  = tar.bz2
PASTIX_VERSION = 5.2.2.22
PASTIX_PKG     = $(PASTIX_NAME)_$(PASTIX_VERSION).$(PASTIX_SUFFIX)
PASTIX_DIR     = $(PASTIX_PKG:%.$(PASTIX_SUFFIX)=%)

SCOTCH_NAME    = scotch
SCOTCH_VERSION = 6.0.0
SCOTCH_PKG     = $(SCOTCH_NAME)_$(SCOTCH_VERSION)_esmumps.$(SOURCE_SUFFIX)
SCOTCH_DIR     = $(SCOTCH_PKG:%.$(SOURCE_SUFFIX)=%)

TAR_GZ_PKGS    = $(SOURCE_PKG) $(BLACS_PKG) $(FBLASLAPACK_PKG) $(MUMPS_PKG) $(SCOTCH_PKG)
TAR_BZ2_PKGS   = $(PASTIX_PKG)
RPM.EXTRAS     = AutoReq:No
RPM.PREFIX     = $(PKGROOT)
