#%Module1.0

set compilernames [regexp -all -inline {\S+} [regsub -all {/\S*} "ROLLCOMPILER" ""]]
set mpinames [regexp -all -inline {\S+} [regsub -all {/\S*} "ROLLMPI" ""]]

module-whatis "petsc"
module-whatis "Version: VERSION"
module-whatis "Description: petsc"
module-whatis "Compiler: $compilernames"
module-whatis "MPI Flavors: $mpinames"

# Figure out the applicable compiler--either the one whose module was loaded
# when this modulefile was loaded or the one with the most-recently-loaded
# module.  Report an error if neither applies.
if [info exists env(PETSCHOME)] {
  foreach {compiler} $compilernames {
    if {[string first "/$compiler/" $::env(PETSCHOME)] >= 0} {
      break
    }
  }
} elseif [info exists env(LOADEDMODULES)] {
  foreach {module} [split $::env(LOADEDMODULES) :] {
    set module [lindex [split $module /] 0]
    if {[regexp [format {%s(/|\s|$)} $module] $compilernames]} {
      set compiler $module
    }
  }
}
if { ! [info exists compiler] } {
  puts stderr "Need to load a compiler module first"
  exit 1
}

# Figure out the applicable mpi--either the one whose module was loaded
# when this modulefile was loaded or the one with the most-recently-loaded
# module.  Default to first element of ROLLMPI if neither applies.
set mpi [lindex $mpinames 0]
if [info exists env(PETSCHOME)] {
  foreach {mpi} $mpinames {
    if {[string first "/$mpi" $::env(PETSCHOME)] >= 0} {
      break
    }
  }
} elseif [info exists env(LOADEDMODULES)] {
  foreach {module} [split $::env(LOADEDMODULES) :] {
    set module [lindex [split $module /] 0]
    if {[regexp [format {%s(/|\s|$)} $module] $mpinames]} {
      set mpi $module
    }
  }
}

setenv PETSCHOME /opt/petsc/$compiler/$mpi
prepend-path LD_LIBRARY_PATH /opt/petsc/$compiler/$mpi/lib
prepend-path LIBPATH /opt/petsc/$compiler/$mpi/lib
module load scalapack
module load parmetis
module load superlu
