#%Module1.0
module-whatis "trilinos"
module-whatis "Version: VERSION"
module-whatis "Description: trilinos"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
if {! [info exists ::env(MPIHOME)] || ! [info exists ::env(LOADEDMODULES)]} {
  puts stderr "Need to load an mpi module before loading trilinos
  exit 1
}
foreach {x} [list ROLLMPI] {
  # Look for flavor in LOADEDMODULES, delimited by colon or end of string.
  # Can also be followed by / (version number).
  if {[regexp [format {[:^]%s[:/$]} $x] $::env(LOADEDMODULES)]} {
    set mpi $x
    break
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
setenv TRILINOSHOME /opt/trilinos/ROLLCOMPILER/$mpi
prepend-path PATH /opt/trilinos/ROLLCOMPILER/$mpi/bin
prepend-path LD_LIBRARY_PATH /opt/trilinos/ROLLCOMPILER/$mpi/lib
prepend-path LIBPATH /opt/trilinos/ROLLCOMPILER/$mpi/lib
