#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "lapack_ROLLCOMPILER"
module-whatis "Version: VERSION"
prepend-path LD_LIBRARY_PATH /opt/lapack/ROLLCOMPILER/lib
prepend-path LIBPATH /opt/lapack/ROLLCOMPILER/lib
setenv LAPACKHOME /opt/lapack/ROLLCOMPILER

END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; if test ! -e .version; then /bin/ln -s .version.VERSION .version; fi )
