#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "gsl_ROLLCOMPILER"
module-whatis "Version: VERSION"
prepend-path PATH /opt/gsl/ROLLCOMPILER/bin
prepend-path LD_LIBRARY_PATH /opt/gsl/ROLLCOMPILER/lib
prepend-path LIBPATH /opt/gsl/ROLLCOMPILER/lib
setenv GSLHOME /opt/gsl/ROLLCOMPILER
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; if test ! -e .version; then /bin/ln -s .version.VERSION .version; fi )

