#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "octave"
module-whatis "Version: VERSION"
prepend-path PATH /opt/octave/bin
prepend-path LD_LIBRARY_PATH /opt/octave/lib/octave/VERSION
prepend-path LIBPATH /opt/octave/lib/octave/VERSION

END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; if test ! -e .version; then /bin/ln -s .version.VERSION .version; fi )
