#%Module1.0
module-whatis "scalapack"
module-whatis "Version: VERSION"
module-whatis "Description: scalapack"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
# Look for MPI flavor in LOADEDMODULES. If no MPI module is loaded, default to
# first element in ROLLMPI.
set mpi [lindex [split "ROLLMPI" "/ "] 0]
foreach {module} [split $::env(LOADEDMODULES) :] {
  set module [lindex [split $module /] 0]
  if {[regexp [format {%s(/|\s|$)} $module] "ROLLMPI"]} {
    set mpi $module
  }
}
setenv SCALAPACKHOME /opt/scalapack/ROLLCOMPILER/$mpi
prepend-path LD_LIBRARY_PATH /opt/scalapack/ROLLCOMPILER/$mpi/lib
prepend-path LIBPATH /opt/scalapack/ROLLCOMPILER/$mpi/lib
